apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: s8535/todo:02  
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb+srv://root:XHyZVbDB8nRF9IYl@cluster.4qlbuab.mongodb.net/"
        - name: SECRET_KEY
          value: "your_secret_key"
