apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: LoadBalancer  # Can also be NodePort or ClusterIP
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
