apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-auth
  template:
    metadata:
      labels:
        app: flask-auth
    spec:
      containers:
      - name: flask-auth
        image: s8535/auth_service:latest  
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb+srv://root:XHyZVbDB8nRF9IYl@cluster.4qlbuab.mongodb.net/"
        - name: DB_NAME
          value: "Microservice"
        - name: SECRET_KEY
          value: "your_secret_key"
