apiVersion: v1
kind: Service
metadata:
  name: flask-auth-service
spec:
  type: LoadBalancer  # Can also be NodePort or ClusterIP
  selector:
    app: flask-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
